$importFile = Import-CSV "C:\Scripts\AutoTask Imports\TestImport.csv" -Header "First Name [Required]", "Last Name [Required]", "Email Address [Required]", "Password [Required]","Password Hash Function [UPLOAD ONLY]","Org Unit Path [Required]" | Select -skip 1

$schoolDict = @{
"Acomb Primary School" = "1199";
"Admiral Long School" = "1344";
"Alderman Cogan" = "1278";
"All Saints RC School" = "1211";
"All Saints Church of England Federation of Academies Hessle" = "1279";
"Applefields School" = "1230";
"Archbishop Holgate's School" = "1200";
"Archbishop of York's Church of England Junior School" = "1314";
"Archbishop Sentamu Academy" = "1311";
"Aspire Academy" = "1374";
"Badger Hill Primary Academy" = "1306";
"Balcomm Ltd" = "1393";
"Baldersby St James Church of England Primary School" = "1262";
"Barkston Ash Catholic Primary School" = "1308";
"Barlby High School" = "1139";
"Birstwith C of E Primary School" = "1345";
"Bishopthorpe Infant School" = "1231";
"Braeburn" = "1281";
"Brotherton and Byram Community Primary Academy" = "1282";
"Broughton Primary School" = "1317";
"Burton Green Primary School" = "1263";
"Camblesforth Community Primary Academy" = "1283";
"Carr Infant School" = "1232";
"Carr Junior School" = "1255";
"Clifton Green Primary School" = "1233";
"Clifton With Rawcliffe Primary School" = "1201";
"Coast and Vale Learning Trust" = "1378";
"Colville Primary School" = "1156";
"Compass Academy" = "1355";
"Copmanthorpe Primary School" = "1234";
"Danesgate Community" = "1235";
"Dringhouses Primary School" = "1236";
"Easington CofE Primary Academy" = "1284";
"Easingwold Community Primary School" = "1237";
"Ebor Academy Filey" = "1285";
"Ebor Academy Trust" = "1210";
"Elvington CofE VC Primary School" = "1238";
"Filey Church of England Nursery and Infants Academy" = "1300";
"Filey School" = "1379";
"Fishergate Primary School" = "1239";
"Forest of Galtres School" = "1264";
"George Pinder School" = "1133";
"Graham School" = "1140";
"Green Hammerton CofE Primary School" = "1240";
"Green Lane Primary Academy" = "1346";
"Haxby Road Primary Academy" = "1286";
"Hempland Primary Academy" = "1202";
"Heworth CofE Primary Academy" = "1203";
"Hilderthorpe Primary School" = "1307";
"Hob Moor Community Primary Academy" = "1287";
"Hob Moor Oaks Academy" = "1288";
"Hope Learning Trust, York" = "1265";
"Howitt Primary Community School" = "1367";
"Huntington Primary Academy" = "1241";
"Huntington School" = "1084";
"Joseph Rowntree School" = "1242";
"Kirk Hammerton Church of England Primary School" = "1309";
"Knavesmire Primary School" = "1256";
"Lakeside Primary Academy" = "1289";
"Long Marston CE Primary School" = "1315";
"Lord Deramore's Primary School" = "1243";
"Manor Church of England Academy  " = "1142";
"Marfleet Primary School" = "1290";
"Millthorpe School" = "1257";
"Mounts Bay Academy" = "1129";
"Naburn CofE Primary School" = "1244";
"New Earswick Primary School" = "1204";
"Newland St Johns CE Academy" = "1363";
"Nicholas Postgate Catholic Academy Trust" = "1392";
"Osbaldwick Primary Academy" = "1291";
"Our Lady and St Peter Catholic Primary School" = "1212";
"Our Lady Queen of Martyrs Catholic Primary School" = "1213";
"Park Grove Primary Academy" = "1292";
"Pathfinder Multi Academy Trust" = "1205";
"Patrington CofE Primary Academy" = "1293";
"Poppleton Ousebank Primary School" = "1266";
"Poppleton Road Primary School" = "1310";
"Riston Church of England Primary Academy" = "1325";
"Robert Wilkinson Primary Academy" = "1294";
"Rufforth Primary School" = "1206";
"Sacred Heart Catholic Primary School - DL7 8UL" = "1214";
"Scarborough University Technical College" = "1377";
"Scarcroft Primary School" = "1258";
"Sigglesthorne CofE Primary Academy" = "1295";
"Skelton Primary School" = "1267";
"South Bank Multi Academy Trust" = "1259";
"Sproatley Endowed CofE Academy" = "1296";
"St Aelred's Catholic Primary School" = "1215";
"St Augustine's Catholic School" = "1216";
"St Barnabas CofE VC Primary School" = "1245";
"St Benedict's Catholic Primary School" = "1217";
"St Francis Xavier School" = "1218";
"St Georges Catholic Primary School Scarborough" = "1219";
"St George's Catholic Primary School York" = "1220";
"St James CE Academy" = "1364";
"St John of Beverley Catholic Primary School" = "1221";
"St Joseph's Catholic Primary School" = "1222";
"St Lawrence's CofE Primary Academy" = "1207";
"St Margaret Clitherow Catholic Academy Trust" = "1223";
"St Mary & St Joseph Catholic Primary School" = "1224";
"St Mary's C Of E Primary School Askham Richard" = "1343";
"St Mary's Catholic Primary School Malton" = "1225";
"St Mary's Catholic Primary School Market Weighton" = "1226";
"St Mary's Catholic Primary School Richmond" = "1227";
"St Marys Church of England Primary School, Boston Spa" = "1312";
"St Oswald's CE VC Primary School" = "1246";
"St Paul's CofE VC Primary School" = "1247";
"St Peter's Catholic Primary School" = "1228";
"St Wilfrid's Catholic Primary School" = "1229";
"Staveley Community Primary School" = "1313";
"Staynor Hall Primary Academy" = "1297";
"Stockton on the Forest Primary School" = "1248";
"Sutton on the Forest CofE VC Primary School" = "1249";
"Tadcaster Primary Academy" = "1298";
"Tang Hall Primary Academy" = "1208";
"Terrington Hall School" = "1250";
"TIG Federation" = "1380";
"Tockwith Church of England Primary Academy" = "1301";
"Vale of York Academy" = "1143";
"Vital Cloud" = "1434";
"Vital York Limited" = "376";
"Westfield Primary Community School" = "1251";
"Wigginton Primary School" = "1252";
"Wingfield Test (VYL Test)" = "1394";
"Woodlesford Primary School" = "1253";
"Woodthorpe Primary School" = "1260";
"Yearsley Grove Primary" = "1254";
"York High School" = "1261";
"York Learning" = "1362";
}

foreach($row in $importFile){
    $fn = $row."First Name [Required]"
    $sn = $row."Last Name [Required]"
    $email = $row."Email Address [Required]"
    $ou = $row."Org Unit Path [Required]"
    $ouWithoutSlash = $ou.Substring(1)
    $SchoolName = $ouWithoutSlash.Substring(0, $ouWithoutSlash.IndexOf('/'))

    if($schoolDict.Keys -match $schoolName){
        $SchoolName
        $schoolDict.$schoolName
    }
}