#Generated Form Function
Import-Module Autotask
function GenerateForm {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
    # Generated On: 23/09/2022 14:54
    # Generated By: rm.mckenzie
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $form1 = New-Object System.Windows.Forms.Form
    $partBox = New-Object System.Windows.Forms.ComboBox
    $label6 = New-Object System.Windows.Forms.Label
    $servicetagBox = New-Object System.Windows.Forms.TextBox
    $label5 = New-Object System.Windows.Forms.Label
    $modelBox = New-Object System.Windows.Forms.TextBox
    $msuBox = New-Object System.Windows.Forms.ComboBox
    $label4 = New-Object System.Windows.Forms.Label
    $label3 = New-Object System.Windows.Forms.Label
    $faultBox = New-Object System.Windows.Forms.ComboBox
    $label2 = New-Object System.Windows.Forms.Label
    $label1 = New-Object System.Windows.Forms.Label
    $companyBox = New-Object System.Windows.Forms.ComboBox
    $submitBtn = New-Object System.Windows.Forms.Button
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects
  
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    
    
    
    
    
    
    
    $handler_form1_Load= 
    {
    #TODO: Place custom script here
    
    }
    
    $handler_button1_Click= 
    {
    #TODO: Place custom script here
        $username = "ewwwsnnpblaybjp@ACADEMIA.CO.UK"
        $password = ConvertTo-SecureString '6j~BT$8db0S*@Ep3Yf2#~Lg4m' -AsPlainText -Force
        $credentials = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $password)
        # Enter your username and password to Autotask
        Connect-AutotaskWebAPI -Credential $Credentials -ApiTrackingIdentifier "BJBWUDOSPVKK23UKZVK3MSQQCMP"

        $vyCompanies = Get-AtwsAccount -UserDefinedField @{name="Support Divison"; value="Vital York"}

        foreach($company in $vyCompanies){
            $sortedCompanies = $company.AccountName
            $companyBox.Items.Add($sortedCompanies)
        }
    }
    
    $OnLoadForm_StateCorrection=
    {#Correct the initial state of the form to prevent the .Net maximized form issue
        $form1.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 716
    $System_Drawing_Size.Width = 1215
    $form1.ClientSize = $System_Drawing_Size
    $form1.DataBindings.DefaultDataSourceUpdateMode = 0
    $form1.Name = "form1"
    $form1.Text = "Primal Form"
    $form1.add_Load($handler_form1_Load)
    
    $partBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $partBox.FormattingEnabled = $True
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 118
    $System_Drawing_Point.Y = 131
    $partBox.Location = $System_Drawing_Point
    $partBox.Name = "partBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 184
    $partBox.Size = $System_Drawing_Size
    $partBox.TabIndex = 15
    
    $form1.Controls.Add($partBox)
    
    $label6.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 108
    $label6.Location = $System_Drawing_Point
    $label6.Name = "label6"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label6.Size = $System_Drawing_Size
    $label6.TabIndex = 14
    $label6.Text = "Service Tag"
    
    $form1.Controls.Add($label6)
    
    $servicetagBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 118
    $System_Drawing_Point.Y = 105
    $servicetagBox.Location = $System_Drawing_Point
    $servicetagBox.Name = "servicetagBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 184
    $servicetagBox.Size = $System_Drawing_Size
    $servicetagBox.TabIndex = 13
    
    $form1.Controls.Add($servicetagBox)
    
    $label5.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 82
    $label5.Location = $System_Drawing_Point
    $label5.Name = "label5"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label5.Size = $System_Drawing_Size
    $label5.TabIndex = 12
    $label5.Text = "Make / Model"
    
    $form1.Controls.Add($label5)
    
    $modelBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 118
    $System_Drawing_Point.Y = 79
    $modelBox.Location = $System_Drawing_Point
    $modelBox.Name = "modelBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 184
    $modelBox.Size = $System_Drawing_Size
    $modelBox.TabIndex = 11
    
    $form1.Controls.Add($modelBox)
    
    $msuBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $msuBox.FormattingEnabled = $True
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 118
    $System_Drawing_Point.Y = 29
    $msuBox.Location = $System_Drawing_Point
    $msuBox.Name = "msuBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 184
    $msuBox.Size = $System_Drawing_Size
    $msuBox.TabIndex = 10
    
    $form1.Controls.Add($msuBox)
    
    $label4.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 32
    $label4.Location = $System_Drawing_Point
    $label4.Name = "label4"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label4.Size = $System_Drawing_Size
    $label4.TabIndex = 9
    $label4.Text = "Managed Service"
    
    $form1.Controls.Add($label4)
    
    $label3.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 134
    $label3.Location = $System_Drawing_Point
    $label3.Name = "label3"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label3.Size = $System_Drawing_Size
    $label3.TabIndex = 7
    $label3.Text = "Part Needed"
    
    $form1.Controls.Add($label3)
    
    $faultBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $faultBox.FormattingEnabled = $True
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 118
    $System_Drawing_Point.Y = 52
    $faultBox.Location = $System_Drawing_Point
    $faultBox.Name = "faultBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 184
    $faultBox.Size = $System_Drawing_Size
    $faultBox.TabIndex = 6
    
    $form1.Controls.Add($faultBox)
    
    $label2.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 9
    $label2.Location = $System_Drawing_Point
    $label2.Name = "label2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label2.Size = $System_Drawing_Size
    $label2.TabIndex = 5
    $label2.Text = "Company / School"
    
    $form1.Controls.Add($label2)
    
    $label1.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 55
    $label1.Location = $System_Drawing_Point
    $label1.Name = "label1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 30
    $label1.Size = $System_Drawing_Size
    $label1.TabIndex = 4
    $label1.Text = "Fault"
    
    $form1.Controls.Add($label1)
    
    $companyBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $companyBox.FormattingEnabled = $True
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 118
    $System_Drawing_Point.Y = 6
    $companyBox.Location = $System_Drawing_Point
    $companyBox.Name = "companyBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 184
    $companyBox.Size = $System_Drawing_Size
    $companyBox.Sorted = $True
    $companyBox.TabIndex = 3
    
    $form1.Controls.Add($companyBox)
    
    
    $submitBtn.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 227
    $System_Drawing_Point.Y = 158
    $submitBtn.Location = $System_Drawing_Point
    $submitBtn.Name = "submitBtn"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $submitBtn.Size = $System_Drawing_Size
    $submitBtn.TabIndex = 2
    $submitBtn.Text = "Submit"
    $submitBtn.UseVisualStyleBackColor = $True
    $submitBtn.add_Click($handler_button1_Click)
    
    $form1.Controls.Add($submitBtn)
        
    #endregion Generated Form Code
    
    #Save the initial state of the form
    $InitialFormWindowState = $form1.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $form1.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $form1.ShowDialog()| Out-Null
    
    } #End Function
    
    #Call the Function
    GenerateForm
    